- name : Configure Docker on EC2 Instances
  hosts : 172.31.21.57:8081
  become : yes
  connection : ssh
  tasks : 
  - name: Deploy Docker Container
    command: docker run -itd -p 8084:8081 anujsharma1990/insure-me:3.0
